# Generated by Django 5.1.1 on 2024-09-10 06:41

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEntry',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('nama_item', models.CharField(max_length=100)),
                ('harga', models.DecimalField(max_digits=10, decimal_places=2)),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
