# Generated by Django 5.1.1 on 2024-09-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_itementry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itementry',
            name='user',
        ),
        migrations.AddField(
            model_name='itementry',
            name='jumlah',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itementry',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itementry',
            name='warna',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itementry',
            name='harga',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itementry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itementry',
            name='nama_item',
            field=models.CharField(max_length=255),
        ),
    ]
