# Generated by Django 5.1.1 on 2024-10-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_itementry_harga_alter_itementry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itementry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itementry',
            name='jumlah',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itementry',
            name='size',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itementry',
            name='warna',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
