# Generated by Django 5.1.1 on 2024-10-01 23:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_itementry_id_alter_itementry_jumlah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itementry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
